### ISSUE TITLE
How do I load a local audio file?

### ISSUE THREAD

**Issue by kierancrown** [vokhuyetOz/react-native-concurrent-sound#1]
The documentation mentions that files can be loaded from either a `http` or `file` url. I've not been able to load local files successful and the example doesn't seem to show how to achieve this?

**Comment by vokhuyetOz** [comment]
how do you get file? from document picker?
which platform was you using? (android or ios)

**Comment by vokhuyetOz** [comment]
it should be 
```
 await load({
      uri: `file://{audio.fileUrl}`,
      key: audio.fileUrl,
      volume: audio.volume / 100,
      loop: false,
  });
```
```
play({
 uri: `file://${audio.fileUrl}`,
 key: audio.fileUrl,
})
```
