### ISSUE TITLE
Crash with New Architecture enabled

### ISSUE THREAD

**Issue by devappsstudio** [vokhuyetOz/react-native-concurrent-sound#13]
Hi,

I tried to run app with New Architecture enabled on emulators and I got crash for both platforms.

package.json
` 
"dependencies": {
    "@react-navigation/elements": "^2.0.0",
    "@react-navigation/native": "^6.1.18",
    "@react-navigation/native-stack": "^6.11.0",
    "@react-navigation/stack": "^6.4.1",
    "@shopify/react-native-skia": "^1.4.2",
    "@vokhuyet/react-native-concurrent-sound": "^0.0.14",
    "react": "18.3.1",
    "react-native": "0.75.4",
    "react-native-gesture-handler": "^2.20.0",
    "react-native-reanimated": "^3.15.5",
    "react-native-safe-area-context": "^4.11.0",
    "react-native-screens": "^3.34.0",
    "react-native-splash-screen": "^3.3.0",
    "zustand": "^5.0.0"
  }
`

For android I got this in terminal:

> Task :app:configureCMakeDebug[arm64-v8a]
> Task :react-native-reanimated:buildCMakeDebug[arm64-v8a]
> Task :react-native-reanimated:buildCMakeDebug[armeabi-v7a]
> Task :react-native-reanimated:buildCMakeDebug[x86]
> Task :react-native-reanimated:buildCMakeDebug[x86_64]

> Task :vokhuyet_react-native-concurrent-sound:compileDebugKotlin FAILED

> Task :react-native-reanimated:externalNativeBuildDebug

Deprecated Gradle features were used in this build, making it incompatible with Gradle 9.0.

You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.

For more on this, please refer to https://docs.gradle.org/8.8/userguide/command_line_interface.html#sec:command_line_warnings in the Gradle documentation.
191 actionable tasks: 25 executed, 166 up-to-date

e: file:///Users/Documents/DEVELOP/react-native/app/node_modules/@vokhuyet/react-native-concurrent-sound/android/src/main/java/com/concurrentsound/ConcurrentSoundModule.kt:23:1 Class 'ConcurrentSoundModule' is not abstract and does not implement abstract base class member public abstract fun load(key: String!, uri: String!, volume: Double, loop: Boolean, promise: Promise!): Unit defined in com.concurrentsound.ConcurrentSoundSpec
e: file:///Users/Documents/DEVELOP/react-native/app/node_modules/@vokhuyet/react-native-concurrent-sound/android/src/main/java/com/concurrentsound/ConcurrentSoundModule.kt:56:3 'load' overrides nothing
e: file:///Users/Documents/DEVELOP/react-native/app/node_modules/@vokhuyet/react-native-concurrent-sound/android/src/main/java/com/concurrentsound/ConcurrentSoundModule.kt:125:3 'setVolume' overrides nothing
e: file:///Users/Documents/DEVELOP/react-native/app/node_modules/@vokhuyet/react-native-concurrent-sound/android/src/main/java/com/concurrentsound/ConcurrentSoundModule.kt:133:3 'setPlaybackRate' overrides nothing

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':vokhuyet_react-native-concurrent-sound:compileDebugKotlin'.
> A failure occurred while executing org.jetbrains.kotlin.compilerRunner.GradleCompilerRunnerWithWorkers$GradleKotlinCompilerWorkAction
   > Compilation error. See log for more details

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
> Get more help at https://help.gradle.org.

BUILD FAILED in 3s

For ios build is succeed. But in terminal I see strange logs: "getAsset 11", "asset 11".
(NOBRIDGE) LOG  Bridgeless mode is enabled
 (NOBRIDGE) LOG  Running "app" with {"rootTag":1,"initialProps":{"concurrentRoot":true},"fabric":true}
 (NOBRIDGE) LOG  getAsset 11
 (NOBRIDGE) LOG  asset 11

When I tried to press button with
 " onPress={async () => {
              const duration = await load({
                key: 'bg_music',
                uri: require('../assets/audio/bg_music.mp3'),
                loop: true,
                volume: 1,
              });
              console.log('Load and Play bg_music assets', duration);
              play({
                key: 'bg_music',
                uri: require('../assets/audio/bg_music.mp3'),
              });
            }}" 
I got the crash:
"
Thread 12 Crashed::  Dispatch queue: com.meta.react.turbomodulemanager.queue
0   app                           	       0x102cbcbc0 Swift runtime failure: force unwrapped a nil value + 0 [inlined]
1   app                           	       0x102cbcbc0 ConcurrentSound.load(key:uri:volume:loop:resolve:reject:) + 2564 (ConcurrentSound.swift:50)
2   app                           	       0x102cbcce8 @objc ConcurrentSound.load(key:uri:volume:loop:resolve:reject:) + 228
3   CoreFoundation                	       0x1804b4720 __invoking___ + 144
4   CoreFoundation                	       0x1804b1a84 -[NSInvocation invoke] + 276
5   CoreFoundation                	       0x1804b1d1c -[NSInvocation invokeWithTarget:] + 60
6   app                           	       0x10283032c invocation function for block in facebook::react::ObjCTurboModule::performMethodInvocation(facebook::jsi::Runtime&, bool, char const*, NSInvocation*, NSMutableArray*) + 240 (RCTTurboModule.mm:347)
7   app                           	       0x102845f24 facebook::react::ObjCTurboModule::performMethodInvocation(facebook::jsi::Runtime&, bool, char const*, NSInvocation*, NSMutableArray*)::$_2::operator()() const + 96 (RCTTurboModule.mm:380)
8   app                           	       0x102845eb8 decltype(std::declval<facebook::react::ObjCTurboModule::performMethodInvocation(facebook::jsi::Runtime&, bool, char const*, NSInvocation*, NSMutableArray*)::$_2&>()()) std::__1::__invoke[abi:ue170006]<facebook::react::ObjCTurboModule::performMethodInvocation(facebook::jsi::Runtime&, bool, char const*, NSInvocation*, NSMutableArray*)::$_2&>(facebook::react::ObjCTurboModule::performMethodInvocation(facebook::jsi::Runtime&, bool, char const*, NSInvocation*, NSMutableArray*)::$_2&) + 24 (invoke.h:340)
9   app                           	       0x102845e70 void std::__1::__invoke_void_return_wrapper<void, true>::__call[abi:ue170006]<facebook::react::ObjCTurboModule::performMethodInvocation(facebook::jsi::Runtime&, bool, char const*, NSInvocation*, NSMutableArray*)::$_2&>(facebook::react::ObjCTurboModule::performMethodInvocation(facebook::jsi::Runtime&, bool, char const*, NSInvocation*, NSMutableArray*)::$_2&) + 24 (invoke.h:415)
10  app                           	       0x102845e4c std::__1::__function::__alloc_func<facebook::react::ObjCTurboModule::performMethodInvocation(facebook::jsi::Runtime&, bool, char const*, NSInvocation*, NSMutableArray*)::$_2, std::__1::allocator<facebook::react::ObjCTurboModule::performMethodInvocation(facebook::jsi::Runtime&, bool, char const*, NSInvocation*, NSMutableArray*)::$_2>, void ()>::operator()[abi:ue170006]() + 28 (function.h:193)
11  app                           	       0x102844bb0 std::__1::__function::__func<facebook::react::ObjCTurboModule::performMethodInvocation(facebook::jsi::Runtime&, bool, char const*, NSInvocation*, NSMutableArray*)::$_2, std::__1::allocator<facebook::react::ObjCTurboModule::performMethodInvocation(facebook::jsi::Runtime&, bool, char const*, NSInvocation*, NSMutableArray*)::$_2>, void ()>::operator()() + 28 (function.h:364)
12  app                           	       0x1021eddb0 std::__1::__function::__value_func<void ()>::operator()[abi:ue170006]() const + 68 (function.h:518)
13  app                           	       0x1021ed848 std::__1::function<void ()>::operator()() const + 24 (function.h:1169)
14  app                           	       0x1028556ec invocation function for block in (anonymous namespace)::ModuleNativeMethodCallInvoker::invokeAsync(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&, std::__1::function<void ()>&&) + 44 (RCTTurboModuleManager.mm:129)
15  libdispatch.dylib             	       0x180170104 _dispatch_call_block_and_release + 24
16  libdispatch.dylib             	       0x180171978 _dispatch_client_callout + 16
17  libdispatch.dylib             	       0x180179b10 _dispatch_lane_serial_drain + 960
18  libdispatch.dylib             	       0x18017a688 _dispatch_lane_invoke + 388
19  libdispatch.dylib             	       0x180185a84 _dispatch_root_queue_drain_deferred_wlh + 276
20  libdispatch.dylib             	       0x1801850d0 _dispatch_workloop_worker_thread + 448
21  libsystem_pthread.dylib       	       0x1079b7814 _pthread_wqthread + 284
22  libsystem_pthread.dylib       	       0x1079b65d4 start_wqthread + 8

Thread 12 crashed with ARM Thread State (64-bit):
    x0: 0x0000000000000000   x1: 0x0000000000000008   x2: 0x0000000000000000   x3: 0x0000000000000000
    x4: 0x005ffc0000000000   x5: 0x0000000000000010   x6: 0x0000000000000000   x7: 0x0000000000000000
    x8: 0x0000000000000001   x9: 0x0000600002c42438  x10: 0x0060001000009100  x11: 0x0000000000000000
   x12: 0xfffffff700000000  x13: 0x0000000800000001  x14: 0x0000004000000001  x15: 0x0020000000000000
   x16: 0x00000001079b6650  x17: 0x00000001d00c6290  x18: 0x0000000000000000  x19: 0x000000016e682120
   x20: 0x000000016e6823f0  x21: 0x000000018005f000  x22: 0x0000000107be7890  x23: 0x0000000107be79d0
   x24: 0x0000600002c264e8  x25: 0x0000000000000000  x26: 0x00000000000010ff  x27: 0x00006000017fb2c0
   x28: 0x0000000000000000   fp: 0x000000016e682540   lr: 0x0000000102cbca78
    sp: 0x000000016e6820d0   pc: 0x0000000102cbcbc0 cpsr: 0x60001000
   far: 0x0000000000000000  esr: 0xf2000001 (Breakpoint) brk 1

"

**Comment by vokhuyetOz** [comment]
Thank you for your feedback 
Actually it is not tested with new arch
I'll check it

**Comment by vokhuyetOz** [comment]
it should be fixed in version 0.1.0
