### ISSUE TITLE
Add option to set playback speed / pitch

### ISSUE THREAD

**Issue by ShivamJoker** [vokhuyetOz/react-native-concurrent-sound#3]
Hi thanks for this library I would like to have the feature to set pitch and playback speed.
Android has the API here: https://developer.android.com/reference/android/media/PlaybackParams#setPitch(float)

**Comment by vokhuyetOz** [comment]
it can be added in next version

**Comment by vokhuyetOz** [comment]
i'm not sure about timeline, i will implement it when i have free time

**Comment by vokhuyetOz** [comment]
any PR is welcome

**Comment by ShivamJoker** [comment]
@vokhuyetOz will send PR for Android by tomorrow.
Also I couldn't get the library to work with the new Architecture.

**Comment by vokhuyetOz** [comment]
Which error did you see?
